import { CheckoutHandler, Header } from '@src/components';
import Head from 'next/head';
import { PageStyle } from '@src/styles';

const CheckoutPage = () => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <PageStyle.Container>
          <CheckoutHandler />
        </PageStyle.Container>
      </main>
    </>
  );
};

export default CheckoutPage;
