import { FeaturedProducts, Header } from '@src/components';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = ({ products }: any) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <FeaturedProducts />
      </main>
      <footer>
        <p>Todos os direitos reservados.</p>
      </footer>
    </>
  );
};

export default Home;
